# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  - OpenZeppelin/openzeppelin-contracts@4.3.2

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'


# automatically fetch contract sources from Etherscan
autofetch_sources: True

dotenv: .env

# set a custom mnemonic for the development network
networks:
  default: rinkeby

  # Here we are testing only in rinkeby testnet but you can set it for any other one
  rinkeby:
    # vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    link_token: '0x01be23585060835e02b77ef475b0cc51aa1e0709'
    # keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000

    # NOTE: Set your own oracle address and job IDs here
    # Bellow address are from my local chainlink node jobs so it can't be used anywhere else
    oracle: '0xec5368C5C258412B8518AEeb6966FAE07d0fc545'
    all_in_system_jobId: '5787b0018e624c0fa81b36573cc766fa'
    is_project_jobId: '5c0a8996ef474b37874a59d511058829'
    sender_auth_jobId: '3f0baa9f71ad49d59cb11aeab10686a7'
    receiver_auth_jobId: '5136b192a71c476a90631dbb00a1201d'

    # Change to True if you have an Etherscan API key and want to verify
    verify: False


wallets:
  from_key: ${PRIVATE_KEY}
  
user_addresses:
  org: ${ORG_ADDRESS}
  user1: ${USER1_ADDRESS}
  user2: ${USER2_ADDRESS}
  user3: ${USER3_ADDRESS}
  user4: ${USER4_ADDRESS}

user_login_tokens:
  org: ${ORG_TOKEN}
  user1: ${USER1_TOKEN}
  user2: ${USER2_TOKEN}
  user3: ${USER3_TOKEN}
  user4: ${USER4_TOKEN}